we did it
lmaraite/tcp-server pull request #25
Opened 2021-05-26 08:57 UTC by Codor77

sollte so weit alles drinn sein

2021-05-27 15:29 UTC, lmaraite requested changes

2021-05-27 15:29 UTC, lmaraite commented on test/datenhaltung.c
> +}
DRY ;-)
Ich könnte am Wochenende vernünftige Tests schreiben .... aber das würd ich nicht in den master lassen

2021-05-27 15:29 UTC, lmaraite commented on src/datenhaltung.c
> +int delete(char* key){
rename in delete_by_key

2021-05-27 15:29 UTC, lmaraite commented on src/datenhaltung.c
> +char *storage = "storage/";
Gehört in die Methode wo es benutzt wird ....

2021-06-07 22:44 UTC, cvonder1 approved these changes
Würde Leon bei den Tests zustimmen. Vorallem weil der return code immer 0 ist.
Können wir aber später noch schauen, ich merge das erst Mal in den dev branch.

2021-06-07 22:44 UTC, merged