Enhancement/#34 exclusive access
lmaraite/tcp-server pull request #41
Opened 2021-06-11 17:05 UTC by Toole-Kartofel

2021-06-14 12:09 UTC, cvonder1 requested changes
A lot of tests fail as well.

2021-06-14 12:09 UTC, cvonder1 commented on src/applicationLayer.c
> +  fclose(exclusiveFile);
This is not completely atomic and therefore prone to race conditions.
E.g.:
```
Client-Thread 1: fopen(".exclusive", "r");
Client-Thread 2: fopen(".exclusive", "r");
...
```
Both clients will return, that they are in the locked state, which is illegal.
Secondly `fprintf` is described as MT-Safe locale. On the man page [attributes](https://www.man7.org/linux/man-pages/man7/attributes.7.html) the locale attribute is explained as follows:

> locale 
>               Functions annotated with locale as an MT-Safety issue read
>               from the locale object without any form of
>               synchronization.  Functions annotated with locale called
>               concurrently with locale changes may behave in ways that
>               do not correspond to any of the locales active during
>               their execution, but an unpredictable mix thereof.
>               We do not mark these functions as MT-Unsafe, however,
>               because functions that modify the locale object are marked
>               with const:locale and regarded as unsafe.  Being unsafe,
>               the latter are not to be called when multiple threads are
>               running or asynchronous signals are enabled, and so the
>               locale can be considered effectively constant in these
>               contexts, which makes the former safe.

I don't find this explanation very intuitive, but as far as I understand it, this means that concurrent calls to `fprintf` might produce gibberish but don't crash the program.
This would result in an program which is locked forever, because in the .exclusive file is no correct pid.
Also the first opened file descriptor in line 32 is not closed.

Principally I very much like the idea to persist the exclusive state across restarts, but I see the problem here, that you cannot associate the exclusive access to a particular client, because we do not have a client identifier.

I see two possible solutions here:
1. use semaphores
2. use read/write functions, since they are atomic, and remove the .exclusive file on startup. After the first call to fopen in line 32, it must be guaranteed for all following calls to fopen to not return a NULL pointer. Therefore it must open the file already with the write option.(fopen is MT-Safe).

    I don't really know, what should happen if client 1 is during it's locking procedure and client 2 wants to perform a request. Is the access already locked? E.g.:
    ```
    Client-Thread 1: fopen(".exclusive", "r");
    Client-Thread 2: ...
    Client-Thread 2: put(command.key, command.value);
    Client-Thread 1: ...
    Client-Thread 1: fprintf(exclusiveFile, "%d", getpid());
    ```
    I guess that would be more well-defined with semaphores, because they make the whole locking mechanism atomic.

2021-06-14 12:09 UTC, cvonder1 commented on include/utils.h
> +    int malloced;
Why did you introduce this variable. Is there any downside to use malloc for all strings?
The variable name is a little misleading, when `malloced` is true(>0) I would assume the value string to be allocated by malloc. But the variable is used the other way around.

2021-06-14 12:09 UTC, cvonder1 commented on src/applicationLayer.c
> +      if(exclusiveStatus==0){
The indentation is not the same as in other lines. This repeats in several lines.

2021-06-15 15:44 UTC, cvonder1 commented on src/applicationLayer.c
> +  fclose(exclusiveFile);
Sry, forget what I have written under point 2, that shouldn't work either.

2021-06-21 14:01 UTC, closed without merging

2021-06-21 14:11 UTC, Codor77 commented on src/applicationLayer.c
> +  fclose(exclusiveFile);
1. wir sind unter uns, längere und kompliziertere Texte daher gerne auf Deutsch...
2. der filedescriptor aus Zeile 32 wird in Zeile 35 im if() geschlossen, sofern der File existiert. Sollte er jedoch nicht existieren, muss der filedescriptor nicht geschlossen werden, da er eh nie geöffnet werden konnte... bitte korrigiere mich, wenn ich da falsch liege.
3. der exclusive Zugriff wird beim QUIT beendet, daher wäre das ganze nur im falle einer abgeschmierten client-session dauerhaft persistent -> können dem aber trotzdem entgegen wirken, indem wir den .exclusive FIle beim Start des servers löschen...
4. semaphoren für beg() und end() sind in der neuesten Version mit drinn, aber ijm gesammtverlauf der BEG/END aktion kann es trotzdem passieren, dass einem User der exclusive Zugriff versprochen wird, er ihn allerdings nicht erhalten hat... wir arbeiten dran